name: 'Sort imports'
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
     - uses: jose-lpa/python-isort-check-action@master
