name: 'PyAction'
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: rahul-deepsource/pyaction@1.4.0
        with:
          python-root-list: "src/ tests/"
          use-mypy: true
          use-black: false
